# Copyright Altoros. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

#intended to easy overwrite base.yaml's configuration in derived projects

version: '2'
services:
  peer-base:
     extends:
       file: base.yaml
       service: peer-base

  couchdb-base:
     extends:
       file: base.yaml
       service: couchdb-base

  cli-base:
    extends:
      file: base.yaml
      service: cli-base


  api-base:
    extends:
      file: base.yaml
      service: api-base


  # explorer-database:
  #   extends:
  #     file: base.yaml
  #     service: explorer_database-base


  # explorer:
  #   extends:
  #     file: base.yaml
  #     service: explorer-base

  www-base:
    extends:
      file: base.yaml
      service: www-base
